import { Connection } from './app/connection/connection';
import './sass/_style.scss';
import { createMainComponent } from './app/pages/main-base';
import { renderLoginContent } from './app/pages/login';
import { UserService } from './app/pages/user-service';
const connection = new Connection();
connection.connect();
const userService = new UserService(connection);
createMainComponent();
renderLoginContent(connection, userService);
